using Finance.Domain.Events;
using Finance.Domain.ValueObjects;

namespace Finance.Domain.Aggregates;

/// <summary>
/// ONE dated cost — a single bill, not a repeating arrangement.
///
/// A one-off has no schedule. A repeating one is generated by <see cref="ChargeSchedule"/> at
/// <see cref="OccurrenceDate"/>, and keeps the amount and split that applied then: that is why
/// amending a schedule never rewrites a month already recorded.
///
/// GroupId discriminates: null is personal, set is shared.
/// </summary>
public class Charge : IAggregateRoot
{
    private readonly List<DomainEvent> _domainEvents = new();

    public ChargeId Id { get; private set; }
    public UserId UserId { get; private set; }

    public GroupId? GroupId { get; private set; }

    /// <summary>The agreement that generated this one. Null means somebody entered it directly.</summary>
    public ChargeScheduleId? ScheduleId { get; private set; }

    /// <summary>
    /// Which of the caller's own accounts paid for it — a card, or checking. Personal only; a
    /// group charge names its funder through FundingSource instead.
    ///
    /// Null means their cash account, which is the honest default: somebody who has told us about
    /// no accounts still spent real money, and the alternative is refusing to record it.
    /// </summary>
    public Guid? FundingAccountId { get; private set; }

    /// <summary>
    /// The date this charge BELONGS to, which is not the date it was written down. For a
    /// generated charge it is the occurrence the schedule named; for a one-off it is the due
    /// date. Unique with ScheduleId, so one occurrence cannot be generated twice.
    /// </summary>
    public DateTime OccurrenceDate { get; private set; }

    public UserId? CreatedBy { get; private set; }

    /// <summary>Who FRONTED the bill — not necessarily who created it.</summary>
    public Guid? PayerUserId { get; private set; }

    /// <summary>
    /// PayerMember: the payer fronts it and debtors repay them. GroupCash: paid from the
    /// pool, and EVERY member settles — the payer included. Meaningless when personal.
    /// </summary>
    public FundingSource FundingSource { get; private set; }

    public string Title { get; private set; } = string.Empty;
    public string? Description { get; private set; }
    public Money Amount { get; private set; }
    public ChargeCategory Category { get; private set; }
    public DateTime DueDate { get; private set; }
    public RecurrenceSchedule? RecurrenceSchedule { get; private set; }
    public DateTime CreatedAt { get; private set; }
    public DateTime UpdatedAt { get; private set; }
    public bool IsActive { get; private set; }

    public IReadOnlyList<DomainEvent> GetDomainEvents() => _domainEvents.AsReadOnly();
    public void ClearDomainEvents() => _domainEvents.Clear();

    private Charge()
    {
    }

    /// <summary>Creates a personal expense (GroupId = null).</summary>
    public static Charge Create(
        UserId userId,
        string title,
        Money amount,
        ChargeCategory category,
        DateTime dueDate,
        RecurrenceSchedule? recurrenceSchedule = null,
        string? description = null,
        Guid? fundingAccountId = null)
    {
        if (string.IsNullOrWhiteSpace(title))
            throw new ArgumentException("Title cannot be empty.", nameof(title));
        if (amount.Amount < 0)
            throw new ArgumentException("Amount cannot be negative.", nameof(amount));

        var expense = new Charge
        {
            Id = ChargeId.New(),
            UserId = userId,
            GroupId = null,
            CreatedBy = null,
            FundingAccountId = fundingAccountId,
            Title = title,
            Description = description,
            Amount = amount,
            Category = category,
            DueDate = DateTime.SpecifyKind(dueDate, DateTimeKind.Utc),
            OccurrenceDate = DateTime.SpecifyKind(dueDate.Date, DateTimeKind.Utc),
            RecurrenceSchedule = recurrenceSchedule,
            CreatedAt = DateTime.UtcNow,
            UpdatedAt = DateTime.UtcNow,
            IsActive = true,
        };

        expense._domainEvents.Add(new ChargeCreated(
            expense.Id,
            userId,
            title,
            amount,
            category,
            dueDate,
            recurrenceSchedule));

        return expense;
    }

    /// <summary>
    /// Materialises the occurrence a schedule placed on <paramref name="occurrenceDate"/>.
    ///
    /// Everything that can drift — amount, category, title, who fronts it — is COPIED from the
    /// schedule now and never read from it again. That copy is what makes the month final: amend
    /// the schedule afterwards and this charge does not move.
    ///
    /// The amount is the one in force ON THAT DATE, not today's, so a month recorded late still
    /// bills what was agreed at the time.
    ///
    /// Refuses a date the schedule does not actually place a charge on, so a caller cannot invent
    /// an occurrence the agreement never described.
    /// </summary>
    public static Charge GenerateFrom(ChargeSchedule schedule, DateTime occurrenceDate)
    {
        ArgumentNullException.ThrowIfNull(schedule);

        var day = DateTime.SpecifyKind(occurrenceDate.Date, DateTimeKind.Utc);
        if (!schedule.Covers(day))
            throw new InvalidOperationException(
                $"{schedule.Title} places no charge on {day:yyyy-MM-dd}.");

        var now = DateTime.UtcNow;
        var charge = new Charge
        {
            Id = ChargeId.New(),
            UserId = schedule.UserId,
            GroupId = schedule.GroupId,
            ScheduleId = schedule.Id,
            OccurrenceDate = day,
            CreatedBy = schedule.CreatedBy,
            PayerUserId = schedule.PayerUserId,
            FundingSource = schedule.FundingSource,
            Title = schedule.Title,
            Description = schedule.Description,
            Amount = schedule.AmountOn(day),
            Category = schedule.Category,
            DueDate = day,
            // The repetition lives on the schedule. Copying it here would give the charge a second
            // opinion about when it recurs, and the read side would have two answers to one question.
            RecurrenceSchedule = null,
            CreatedAt = now,
            UpdatedAt = now,
            IsActive = true,
        };

        charge._domainEvents.Add(new ChargeCreated(
            charge.Id, schedule.UserId, schedule.Title, schedule.AmountOn(day), schedule.Category, day, null));

        return charge;
    }

    /// <summary>UserId is set to the CREATOR here, unlike a personal charge's owner.</summary>
    public static Charge CreateGroup(
        GroupId groupId,
        UserId createdBy,
        string title,
        Money amount,
        ChargeCategory category,
        DateTime dueDate,
        RecurrenceSchedule? recurrenceSchedule = null,
        string? description = null,
        Guid? payerUserId = null,
        FundingSource fundingSource = FundingSource.PayerMember)
    {
        if (string.IsNullOrWhiteSpace(title))
            throw new ArgumentException("Title cannot be empty.", nameof(title));
        if (amount.Amount < 0)
            throw new ArgumentException("Amount cannot be negative.", nameof(amount));

        var expense = new Charge
        {
            Id = ChargeId.New(),
            UserId = createdBy,
            GroupId = groupId,
            CreatedBy = createdBy,
            PayerUserId = payerUserId,
            FundingSource = fundingSource,
            Title = title,
            Description = description,
            Amount = amount,
            Category = category,
            DueDate = DateTime.SpecifyKind(dueDate, DateTimeKind.Utc),
            OccurrenceDate = DateTime.SpecifyKind(dueDate.Date, DateTimeKind.Utc),
            RecurrenceSchedule = recurrenceSchedule,
            CreatedAt = DateTime.UtcNow,
            UpdatedAt = DateTime.UtcNow,
            IsActive = true,
        };

        expense._domainEvents.Add(new ChargeCreated(
            expense.Id,
            createdBy,
            title,
            amount,
            category,
            dueDate,
            recurrenceSchedule,
            groupId,
            payerUserId));

        return expense;
    }

    public void Update(
        string title,
        Money amount,
        ChargeCategory category,
        DateTime dueDate,
        RecurrenceSchedule? recurrenceSchedule = null,
        string? description = null,
        Guid? payerUserId = null)
    {
        if (string.IsNullOrWhiteSpace(title))
            throw new ArgumentException("Title cannot be empty.", nameof(title));
        if (amount.Amount < 0)
            throw new ArgumentException("Amount cannot be negative.", nameof(amount));

        Title = title;
        Amount = amount;
        Category = category;
        DueDate = DateTime.SpecifyKind(dueDate, DateTimeKind.Utc);
        // OccurrenceDate deliberately does NOT follow. It is which period this charge belongs to,
        // and moving that would restate a month that has already been reported.
        RecurrenceSchedule = recurrenceSchedule;
        Description = description;
        // Only mutate payer when explicitly supplied; null on personal expenses, optional on group
        if (GroupId is not null && payerUserId is not null)
            PayerUserId = payerUserId;
        UpdatedAt = DateTime.UtcNow;

        _domainEvents.Add(new ChargeUpdated(Id, title, amount, category, dueDate, recurrenceSchedule, GroupId, PayerUserId));
    }

    public void Deactivate()
    {
        if (!IsActive)
            throw new InvalidOperationException("Charge is already inactive.");

        IsActive = false;
        UpdatedAt = DateTime.UtcNow;

        _domainEvents.Add(new ChargeDeactivated(Id, GroupId));
    }

    public void Activate()
    {
        if (IsActive)
            throw new InvalidOperationException("Charge is already active.");

        IsActive = true;
        UpdatedAt = DateTime.UtcNow;
        _domainEvents.Add(new ChargeActivated(Id, GroupId));
    }

    public bool TryDeactivate()
    {
        if (!IsActive) return false;
        Deactivate();
        return true;
    }

    /// <summary>
    /// Record that the vendor was paid for this group charge — fronted from a member's pocket
    /// (<see cref="FundingSource.PayerMember"/>, with <paramref name="paidByUserId"/> the payer) or
    /// from the shared pot (<see cref="FundingSource.GroupCash"/>). Sets the funding of record (which
    /// member settlement reads) and raises the fact. The ledger posting (Dr Vendor Payable / Cr the
    /// funding account) is recorded separately by the application layer; "is it paid" is derived from
    /// the ledger (Vendor Payable balance), not stored here.
    /// </summary>
    public void RecordVendorPayment(DateTime occurrenceDate, FundingSource fundingSource, Guid? paidByUserId)
    {
        if (GroupId is null)
            throw new InvalidOperationException("Vendor payment applies to group charges only.");

        FundingSource = fundingSource;
        if (fundingSource == FundingSource.PayerMember && paidByUserId is not null)
            PayerUserId = paidByUserId;
        UpdatedAt = DateTime.UtcNow;

        var occurrence = DateTime.SpecifyKind(occurrenceDate.Date, DateTimeKind.Utc);
        _domainEvents.Add(new VendorPaid(Id, occurrence, fundingSource, paidByUserId, DateTime.UtcNow));
    }

    /// <summary>Undo the vendor payment for an occurrence (the ledger reversal is posted by the
    /// application layer). The funding of record is left in place as the intended default.</summary>
    public void ReverseVendorPayment(DateTime occurrenceDate)
    {
        if (GroupId is null)
            throw new InvalidOperationException("Vendor payment applies to group charges only.");

        UpdatedAt = DateTime.UtcNow;
        var occurrence = DateTime.SpecifyKind(occurrenceDate.Date, DateTimeKind.Utc);
        _domainEvents.Add(new VendorPaymentReversed(Id, occurrence));
    }
}
