using Finance.Domain.Events;
using Finance.Domain.ValueObjects;

namespace Finance.Domain.Aggregates;

/// <summary>
/// ONE dated cost — a single bill, not a repeating arrangement.
///
/// A one-off has no schedule. A repeating one is generated by <see cref="ChargeSchedule"/> at
/// <see cref="OccurrenceDate"/>, and keeps the amount and split that applied then: that is why
/// amending a schedule never rewrites a month already recorded.
///
/// It belongs to ONE accounting entity — a household or a person — and somebody entered it. Those
/// are two different facts, and they used to be three fields saying them: a UserId that meant the
/// owner on a personal charge and the author on a shared one, a nullable GroupId doubling as the
/// discriminator, and a CreatedBy that repeated the UserId. There is no such thing as a "group
/// charge"; there is a charge, and an entity whose books it lands in.
/// </summary>
public class Charge : IAggregateRoot
{
    private readonly List<DomainEvent> _domainEvents = new();

    public ChargeId Id { get; private set; }

    /// <summary>Whose books this lands in.</summary>
    public AccountingEntity Owner { get; private set; }

    /// <summary>The person who wrote it down. On a charge somebody keeps for themselves this is
    /// also the owner; on a household's it is whoever entered it for the house.</summary>
    public UserId EnteredBy { get; private set; }

    /// <summary>The household when this is one of theirs, null when it is somebody's own. Kept for
    /// the events other services consume, which still speak in group ids.</summary>
    public GroupId? GroupId => Owner.AsGroup;

    /// <summary>The agreement that generated this one. Null means somebody entered it directly.</summary>
    public ChargeScheduleId? ScheduleId { get; private set; }

    /// <summary>
    /// Which of the caller's own accounts paid for it — a card, or checking. Personal only; a
    /// group charge names its funder through FundingSource instead.
    ///
    /// Null means their cash account, which is the honest default: somebody who has told us about
    /// no accounts still spent real money, and the alternative is refusing to record it.
    /// </summary>
    public Guid? FundingAccountId { get; private set; }

    /// <summary>
    /// The date this charge BELONGS to, which is not the date it was written down. For a
    /// generated charge it is the occurrence the schedule named; for a one-off it is the due
    /// date. Unique with ScheduleId, so one occurrence cannot be generated twice.
    /// </summary>
    public DateTime OccurrenceDate { get; private set; }

    /// <summary>Who FRONTED the bill — not necessarily who created it.</summary>
    public Guid? PayerUserId { get; private set; }

    /// <summary>
    /// PayerMember: the payer fronts it and debtors repay them. GroupCash: paid from the
    /// pool, and EVERY member settles — the payer included. Meaningless when personal.
    /// </summary>
    public FundingSource FundingSource { get; private set; }

    public string Title { get; private set; } = string.Empty;
    public string? Description { get; private set; }
    public Money Amount { get; private set; }
    public ChargeCategory Category { get; private set; }
    public DateTime DueDate { get; private set; }
    public DateTime CreatedAt { get; private set; }
    public DateTime UpdatedAt { get; private set; }
    public bool IsActive { get; private set; }

    /// <summary>
    /// May this person change the bill itself — its amount, its split, whether the vendor is paid?
    ///
    /// Whoever entered it, matching the rule the vendor-payment paths already enforce. Membership
    /// alone is not enough: being in the house lets you see a bill and settle your own share, not
    /// re-cut how it was divided.
    /// </summary>
    public bool IsManagedBy(Guid userId) => EnteredBy.Value == userId;

    /// <summary>
    /// A charge this person keeps for themselves. A household's is never "own" — it is reached
    /// through membership, which is a different question with a different answer.
    /// </summary>
    public bool IsOwnedBy(Guid userId) => Owner.Is(userId);

    /// <summary>
    /// Settles a personal charge from whatever funded it. Raises the fact; the books are kept by
    /// whoever consumes it, so this never decides what the posting looks like.
    /// </summary>
    public void RecordPersonalPayment(Guid? fundingAccountId, DateTime paidAt)
    {
        if (Owner.IsHousehold)
            throw new InvalidOperationException("A shared charge is settled through its allocations.");

        if (fundingAccountId is not null) FundingAccountId = fundingAccountId;
        UpdatedAt = DateTime.UtcNow;
        _domainEvents.Add(new ChargePaid(Id, EnteredBy, OccurrenceDate, paidAt));
    }

    /// <summary>
    /// Undoes a personal settlement. Raises the fact; the books unwind it with a mirror entry,
    /// because a payment that happened and was undone is two events, not an erasure.
    /// </summary>
    public void ReversePersonalPayment()
    {
        if (Owner.IsHousehold)
            throw new InvalidOperationException("A shared charge is settled through its allocations.");

        UpdatedAt = DateTime.UtcNow;
        _domainEvents.Add(new ChargeUnpaid(Id, EnteredBy, OccurrenceDate));
    }

    public IReadOnlyList<DomainEvent> GetDomainEvents() => _domainEvents.AsReadOnly();
    public void ClearDomainEvents() => _domainEvents.Clear();

    private Charge()
    {
    }

    /// <summary>
    /// One bill somebody entered directly. <paramref name="owner"/> says whose books it lands in —
    /// a household's or that person's own — and there is no second factory for the other case,
    /// because nothing else about the bill turns on which it is.
    /// </summary>
    public static Charge Create(
        AccountingEntity owner,
        UserId enteredBy,
        string title,
        Money amount,
        ChargeCategory category,
        DateTime dueDate,
        string? description = null,
        Guid? fundingAccountId = null,
        Guid? payerUserId = null,
        FundingSource fundingSource = FundingSource.PayerMember)
    {
        if (string.IsNullOrWhiteSpace(title))
            throw new ArgumentException("Title cannot be empty.", nameof(title));
        if (amount.Amount < 0)
            throw new ArgumentException("Amount cannot be negative.", nameof(amount));
        if (owner.IsPerson && !owner.Is(enteredBy.Value))
            throw new InvalidOperationException("Nobody enters a charge into somebody else's own book.");

        var charge = new Charge
        {
            Id = ChargeId.New(),
            Owner = owner,
            EnteredBy = enteredBy,
            // A person funds their own bill from one of their accounts; a household says which
            // side funded it instead. Neither is meaningful on the other.
            FundingAccountId = owner.IsPerson ? fundingAccountId : null,
            PayerUserId = owner.IsHousehold ? payerUserId : null,
            FundingSource = fundingSource,
            Title = title,
            Description = description,
            Amount = amount,
            Category = category,
            DueDate = DateTime.SpecifyKind(dueDate, DateTimeKind.Utc),
            OccurrenceDate = DateTime.SpecifyKind(dueDate.Date, DateTimeKind.Utc),
            CreatedAt = DateTime.UtcNow,
            UpdatedAt = DateTime.UtcNow,
            IsActive = true,
        };

        charge._domainEvents.Add(new ChargeCreated(
            charge.Id, enteredBy, title, amount, category, dueDate,
            charge.GroupId, charge.PayerUserId));

        return charge;
    }

    /// <summary>Somebody's own bill: they own it and they entered it.</summary>
    public static Charge CreateOwn(
        UserId owner,
        string title,
        Money amount,
        ChargeCategory category,
        DateTime dueDate,
        string? description = null,
        Guid? fundingAccountId = null)
        => Create(AccountingEntity.Person(owner), owner, title, amount, category, dueDate,
            description, fundingAccountId);

    /// <summary>
    /// Materialises the occurrence a schedule placed on <paramref name="occurrenceDate"/>.
    ///
    /// Everything that can drift — amount, category, title, who fronts it — is COPIED from the
    /// schedule now and never read from it again. That copy is what makes the month final: amend
    /// the schedule afterwards and this charge does not move.
    ///
    /// The amount is the one in force ON THAT DATE, not today's, so a month recorded late still
    /// bills what was agreed at the time.
    ///
    /// Refuses a date the schedule does not actually place a charge on, so a caller cannot invent
    /// an occurrence the agreement never described.
    /// </summary>
    public static Charge GenerateFrom(ChargeSchedule schedule, DateTime occurrenceDate)
    {
        ArgumentNullException.ThrowIfNull(schedule);

        var day = DateTime.SpecifyKind(occurrenceDate.Date, DateTimeKind.Utc);
        if (!schedule.Covers(day))
            throw new InvalidOperationException(
                $"{schedule.Title} places no charge on {day:yyyy-MM-dd}.");

        var now = DateTime.UtcNow;
        var charge = new Charge
        {
            Id = ChargeId.New(),
            Owner = schedule.Owner,
            EnteredBy = schedule.CreatedBy,
            ScheduleId = schedule.Id,
            OccurrenceDate = day,
            PayerUserId = schedule.PayerUserId,
            FundingSource = schedule.FundingSource,
            Title = schedule.Title,
            Description = schedule.Description,
            Amount = schedule.AmountOn(day),
            Category = schedule.Category,
            DueDate = day,
            CreatedAt = now,
            UpdatedAt = now,
            IsActive = true,
        };

        charge._domainEvents.Add(new ChargeCreated(
            charge.Id, schedule.CreatedBy, schedule.Title, schedule.AmountOn(day), schedule.Category, day));

        return charge;
    }

    public void Update(
        string title,
        Money amount,
        ChargeCategory category,
        DateTime dueDate,
        string? description = null,
        Guid? payerUserId = null)
    {
        if (string.IsNullOrWhiteSpace(title))
            throw new ArgumentException("Title cannot be empty.", nameof(title));
        if (amount.Amount < 0)
            throw new ArgumentException("Amount cannot be negative.", nameof(amount));

        Title = title;
        Amount = amount;
        Category = category;
        DueDate = DateTime.SpecifyKind(dueDate, DateTimeKind.Utc);
        // OccurrenceDate deliberately does NOT follow. It is which period this charge belongs to,
        // and moving that would restate a month that has already been reported.
        Description = description;
        // Only mutate payer when explicitly supplied; meaningless on somebody's own bill.
        if (Owner.IsHousehold && payerUserId is not null)
            PayerUserId = payerUserId;
        UpdatedAt = DateTime.UtcNow;

        _domainEvents.Add(new ChargeUpdated(Id, title, amount, category, dueDate, GroupId, PayerUserId));
    }

    public void Deactivate()
    {
        if (!IsActive)
            throw new InvalidOperationException("Charge is already inactive.");

        IsActive = false;
        UpdatedAt = DateTime.UtcNow;

        _domainEvents.Add(new ChargeDeactivated(Id, GroupId));
    }

    public void Activate()
    {
        if (IsActive)
            throw new InvalidOperationException("Charge is already active.");

        IsActive = true;
        UpdatedAt = DateTime.UtcNow;
        _domainEvents.Add(new ChargeActivated(Id, GroupId));
    }

    public bool TryDeactivate()
    {
        if (!IsActive) return false;
        Deactivate();
        return true;
    }

    /// <summary>
    /// Record that the vendor was paid for this group charge — fronted from a member's pocket
    /// (<see cref="FundingSource.PayerMember"/>, with <paramref name="paidByUserId"/> the payer) or
    /// from the shared pot (<see cref="FundingSource.GroupCash"/>). Sets the funding of record (which
    /// member settlement reads) and raises the fact. The ledger posting (Dr Vendor Payable / Cr the
    /// funding account) is recorded separately by the application layer; "is it paid" is derived from
    /// the ledger (Vendor Payable balance), not stored here.
    /// </summary>
    public void RecordVendorPayment(DateTime occurrenceDate, FundingSource fundingSource, Guid? paidByUserId)
    {
        if (GroupId is null)
            throw new InvalidOperationException("Vendor payment applies to group charges only.");

        FundingSource = fundingSource;
        if (fundingSource == FundingSource.PayerMember && paidByUserId is not null)
            PayerUserId = paidByUserId;
        UpdatedAt = DateTime.UtcNow;

        var occurrence = DateTime.SpecifyKind(occurrenceDate.Date, DateTimeKind.Utc);
        _domainEvents.Add(new VendorPaid(Id, occurrence, fundingSource, paidByUserId, DateTime.UtcNow));
    }

    /// <summary>Undo the vendor payment for an occurrence (the ledger reversal is posted by the
    /// application layer). The funding of record is left in place as the intended default.</summary>
    public void ReverseVendorPayment(DateTime occurrenceDate)
    {
        if (GroupId is null)
            throw new InvalidOperationException("Vendor payment applies to group charges only.");

        UpdatedAt = DateTime.UtcNow;
        var occurrence = DateTime.SpecifyKind(occurrenceDate.Date, DateTimeKind.Utc);
        _domainEvents.Add(new VendorPaymentReversed(Id, occurrence));
    }
}
