using Finance.Domain.Events;
using Finance.Domain.ValueObjects;

namespace Finance.Domain.Aggregates;

/// <summary>
/// ONE dated cost — a single expense, not a repeating arrangement.
///
/// A one-off has no schedule. A repeating one is generated by <see cref="RecurringExpense"/> at
/// <see cref="OccurrenceDate"/>, and keeps the amount and split that applied then: that is why
/// amending a schedule never rewrites a month already recorded.
///
/// It belongs to ONE accounting entity — a group or a person — and somebody entered it. Those are
/// two different facts. There is no such thing as a "group expense"; there is an expense, and an
/// entity whose books it lands in.
/// </summary>
public class Expense : IAggregateRoot
{
    private readonly List<DomainEvent> _domainEvents = new();

    public ExpenseId Id { get; private set; }

    public AccountingEntity Owner { get; private set; }

    /// <summary>The person who wrote it down. On an expense somebody keeps for themselves this is
    /// also the owner; on a group's it is whoever entered it for the group.</summary>
    public UserId EnteredBy { get; private set; }

    /// <summary>The group when this is one of theirs, null when it is somebody's own. Kept for
    /// the events other services consume, which still speak in group ids.</summary>
    public GroupId? GroupId => Owner.AsGroup;

    /// <summary>The agreement that generated this one. Null means somebody entered it directly.</summary>
    public RecurringExpenseId? RecurringExpenseId { get; private set; }

    /// <summary>
    /// Which of the caller's own accounts paid for it — a card, or checking. Personal only; a
    /// group expense names its funder through FundingSource instead.
    ///
    /// Null means their cash account, which is the honest default: somebody who has told us about
    /// no accounts still spent real money, and the alternative is refusing to record it.
    /// </summary>
    public Guid? FundingAccountId { get; private set; }

    /// <summary>
    /// The date this expense BELONGS to, which is not the date it was written down. For a
    /// generated expense it is the occurrence the schedule named; for a one-off it is the due
    /// date. Unique with RecurringExpenseId, so one occurrence cannot be generated twice.
    /// </summary>
    public DateTime OccurrenceDate { get; private set; }

    /// <summary>Who FRONTED the expense — not necessarily who created it.</summary>
    public Guid? PayerUserId { get; private set; }

    /// <summary>
    /// PayerMember: the payer fronts it and debtors repay them. GroupCash: paid from the
    /// pool, and EVERY member settles — the payer included. Meaningless when personal.
    /// </summary>
    public FundingSource FundingSource { get; private set; }

    public string Title { get; private set; } = string.Empty;
    public string? Description { get; private set; }
    public Money Amount { get; private set; }
    public ExpenseCategory Category { get; private set; }
    public DateTime DueDate { get; private set; }
    public DateTime CreatedAt { get; private set; }
    public DateTime UpdatedAt { get; private set; }

    /// <summary>Moves on every change that affects how this expense may be split. Checked on write,
    /// so two people re-cutting the same expense at once cannot both succeed.</summary>
    public uint Version { get; private set; }

    /// <summary>
    /// Marks the expense touched because one of its shares changed.
    ///
    /// Shares are their own rows, so "the shares must not exceed the total" is checked by reading
    /// them and then writing — and two people setting a share at once both read the same total and
    /// both fit. On a £90 expense already split 60, each writes 45 and it lands at 105. The engine
    /// then refuses to journalize it, inside a consumer, where nobody is listening.
    ///
    /// Bumping the version puts the write behind a concurrency check, so the second one fails
    /// instead of overshooting the total. It cannot be an invariant of the aggregate proper: EF cannot
    /// query an owned collection on its own, and both the read side and the share consumer look a
    /// share up by id without knowing its expense.
    ///
    /// Raises no event — the share raises its own.
    /// </summary>
    /// <summary>
    /// Can this expense carry one more share of <paramref name="newShare"/>, given what its other
    /// shares already come to?
    ///
    /// The expense supplies its own total rather than taking it back from the caller: shares
    /// stranded above a total is the case the journalizing engine cannot post, and it fails inside
    /// a consumer where nobody sees it.
    /// </summary>
    public bool CanBear(decimal otherSharesTotal, decimal newShare) =>
        otherSharesTotal + newShare <= Amount.Amount;


    /// <summary>
    /// Only under <see cref="ValueObjects.FundingSource.PayerMember"/>: fronting the expense IS
    /// that member's settlement. Under GroupCash nobody is covered — every share, the payer's
    /// included, is owed into the pot and settled explicitly.
    /// </summary>
    public bool CoversOwnShare(Guid userId) =>
        Owner.IsGroup && FundingSource == FundingSource.PayerMember && PayerUserId == userId;

    public void RecordShareChange()
    {
        Version++;
        UpdatedAt = DateTime.UtcNow;
    }
    public bool IsActive { get; private set; }

    /// <summary>
    /// May this person change the expense itself — its amount, its split, whether the vendor is paid?
    ///
    /// Whoever entered it, matching the rule the vendor-payment paths already enforce. Membership
    /// alone is not enough: being in the group lets you see an expense and settle your own share, not
    /// re-cut how it was divided.
    /// </summary>
    public bool IsManagedBy(Guid userId) => EnteredBy.Value == userId;

    /// <summary>
    /// An expense this person keeps for themselves. A group's is never "own" — it is reached
    /// through membership, which is a different question with a different answer.
    /// </summary>
    public bool IsOwnedBy(Guid userId) => Owner.Is(userId);

    /// <summary>
    /// Settles a personal expense from whatever funded it. Raises the fact; the books are kept by
    /// whoever consumes it, so this never decides what the posting looks like.
    /// </summary>
    public void RecordPersonalPayment(Guid? fundingAccountId, DateTime paidAt)
    {
        if (Owner.IsGroup)
            throw new InvalidOperationException("A shared expense is settled through its shares.");

        if (fundingAccountId is not null) FundingAccountId = fundingAccountId;
        UpdatedAt = DateTime.UtcNow;
        _domainEvents.Add(new ExpensePaid(Id, EnteredBy, OccurrenceDate, paidAt));
    }

    /// <summary>
    /// Undoes a personal settlement. Raises the fact; the books unwind it with a mirror entry,
    /// because a payment that happened and was undone is two events, not an erasure.
    /// </summary>
    public void ReversePersonalPayment()
    {
        if (Owner.IsGroup)
            throw new InvalidOperationException("A shared expense is settled through its shares.");

        UpdatedAt = DateTime.UtcNow;
        _domainEvents.Add(new ExpenseUnpaid(Id, EnteredBy, OccurrenceDate));
    }

    public IReadOnlyList<DomainEvent> GetDomainEvents() => _domainEvents.AsReadOnly();
    public void ClearDomainEvents() => _domainEvents.Clear();

    private Expense()
    {
    }

    /// <summary>
    /// One expense somebody entered directly. <paramref name="owner"/> says whose books it lands in —
    /// a group's or that person's own — and there is no second factory for the other case,
    /// because nothing else about the expense turns on which it is.
    /// </summary>
    public static Expense Create(
        AccountingEntity owner,
        UserId enteredBy,
        string title,
        Money amount,
        ExpenseCategory category,
        DateTime dueDate,
        string? description = null,
        Guid? fundingAccountId = null,
        Guid? payerUserId = null,
        FundingSource fundingSource = FundingSource.PayerMember)
    {
        if (string.IsNullOrWhiteSpace(title))
            throw new ArgumentException("Title cannot be empty.", nameof(title));
        if (amount.Amount < 0)
            throw new ArgumentException("Amount cannot be negative.", nameof(amount));
        if (owner.IsPerson && !owner.Is(enteredBy.Value))
            throw new InvalidOperationException("Nobody enters an expense into somebody else's own book.");

        var expense = new Expense
        {
            Id = ExpenseId.New(),
            Owner = owner,
            EnteredBy = enteredBy,
            // A person funds their own expense from one of their accounts; a group says which
            // side funded it instead. Neither is meaningful on the other.
            FundingAccountId = owner.IsPerson ? fundingAccountId : null,
            PayerUserId = owner.IsGroup ? payerUserId : null,
            FundingSource = fundingSource,
            Title = title,
            Description = description,
            Amount = amount,
            Category = category,
            DueDate = DateTime.SpecifyKind(dueDate, DateTimeKind.Utc),
            OccurrenceDate = DateTime.SpecifyKind(dueDate.Date, DateTimeKind.Utc),
            CreatedAt = DateTime.UtcNow,
            UpdatedAt = DateTime.UtcNow,
            IsActive = true,
        };

        expense._domainEvents.Add(new ExpenseCreated(
            expense.Id, enteredBy, title, amount, category, dueDate,
            expense.GroupId, expense.PayerUserId));

        return expense;
    }

    /// <summary>Somebody's own expense: they own it and they entered it.</summary>
    public static Expense CreateOwn(
        UserId owner,
        string title,
        Money amount,
        ExpenseCategory category,
        DateTime dueDate,
        string? description = null,
        Guid? fundingAccountId = null)
        => Create(AccountingEntity.Person(owner), owner, title, amount, category, dueDate,
            description, fundingAccountId);

    /// <summary>
    /// Materialises the occurrence a schedule placed on <paramref name="occurrenceDate"/>.
    ///
    /// Everything that can drift — amount, category, title, who fronts it — is COPIED from the
    /// schedule now and never read from it again. That copy is what makes the month final: amend
    /// the schedule afterwards and this expense does not move.
    ///
    /// The amount is the one in force ON THAT DATE, not today's, so a month recorded late still
    /// records what was agreed at the time.
    ///
    /// Refuses a date the schedule does not actually place an expense on, so a caller cannot invent
    /// an occurrence the agreement never described.
    /// </summary>
    public static Expense GenerateFrom(RecurringExpense schedule, DateTime occurrenceDate)
    {
        ArgumentNullException.ThrowIfNull(schedule);

        var day = DateTime.SpecifyKind(occurrenceDate.Date, DateTimeKind.Utc);
        if (!schedule.Covers(day))
            throw new InvalidOperationException(
                $"{schedule.Title} places no expense on {day:yyyy-MM-dd}.");

        var now = DateTime.UtcNow;
        var expense = new Expense
        {
            Id = ExpenseId.New(),
            Owner = schedule.Owner,
            EnteredBy = schedule.CreatedBy,
            RecurringExpenseId = schedule.Id,
            OccurrenceDate = day,
            PayerUserId = schedule.PayerUserId,
            FundingSource = schedule.FundingSource,
            Title = schedule.Title,
            Description = schedule.Description,
            Amount = schedule.AmountOn(day),
            Category = schedule.Category,
            DueDate = day,
            CreatedAt = now,
            UpdatedAt = now,
            IsActive = true,
        };

        expense._domainEvents.Add(new ExpenseCreated(
            expense.Id, schedule.CreatedBy, schedule.Title, schedule.AmountOn(day), schedule.Category, day));

        return expense;
    }

    public void Update(
        string title,
        Money amount,
        ExpenseCategory category,
        DateTime dueDate,
        string? description = null,
        Guid? payerUserId = null,
        decimal sharesAlreadyOn = 0m)
    {
        if (string.IsNullOrWhiteSpace(title))
            throw new ArgumentException("Title cannot be empty.", nameof(title));
        if (amount.Amount < 0)
            throw new ArgumentException("Amount cannot be negative.", nameof(amount));
        // Shrinking below what is already divided up would strand those shares above the total.
        // The journalizing engine cannot post that — it fails inside a consumer, where nobody is
        // listening — so it is refused here, at the moment the amount actually changes.
        if (sharesAlreadyOn > amount.Amount)
            throw new InvalidOperationException(
                $"Shares already total {sharesAlreadyOn:0.##}; the expense cannot be less than that.");

        Title = title;
        Amount = amount;
        Category = category;
        Version++;
        DueDate = DateTime.SpecifyKind(dueDate, DateTimeKind.Utc);
        // OccurrenceDate deliberately does NOT follow. It is which period this expense belongs to,
        // and moving that would restate a month that has already been reported.
        Description = description;
        // Only mutate payer when explicitly supplied; meaningless on somebody's own expense.
        if (Owner.IsGroup && payerUserId is not null)
            PayerUserId = payerUserId;
        UpdatedAt = DateTime.UtcNow;

        _domainEvents.Add(new ExpenseUpdated(Id, title, amount, category, dueDate, GroupId, PayerUserId));
    }

    public void Deactivate()
    {
        if (!IsActive)
            throw new InvalidOperationException("Expense is already inactive.");

        IsActive = false;
        UpdatedAt = DateTime.UtcNow;

        _domainEvents.Add(new ExpenseDeactivated(Id, GroupId));
    }

    public void Activate()
    {
        if (IsActive)
            throw new InvalidOperationException("Expense is already active.");

        IsActive = true;
        UpdatedAt = DateTime.UtcNow;
        _domainEvents.Add(new ExpenseActivated(Id, GroupId));
    }

    public bool TryDeactivate()
    {
        if (!IsActive) return false;
        Deactivate();
        return true;
    }

    /// <summary>
    /// Record that the vendor was paid for this group expense — fronted from a member's pocket
    /// (<see cref="FundingSource.PayerMember"/>, with <paramref name="paidByUserId"/> the payer) or
    /// from the shared pot (<see cref="FundingSource.GroupCash"/>). Sets the funding of record (which
    /// member settlement reads) and raises the fact. The ledger posting (Dr Vendor Payable / Cr the
    /// funding account) is recorded separately by the application layer; "is it paid" is derived from
    /// the ledger (Vendor Payable balance), not stored here.
    /// </summary>
    public void RecordVendorPayment(DateTime occurrenceDate, FundingSource fundingSource, Guid? paidByUserId)
    {
        if (GroupId is null)
            throw new InvalidOperationException("Vendor payment applies to group expenses only.");

        FundingSource = fundingSource;
        if (fundingSource == FundingSource.PayerMember && paidByUserId is not null)
            PayerUserId = paidByUserId;
        UpdatedAt = DateTime.UtcNow;

        var occurrence = DateTime.SpecifyKind(occurrenceDate.Date, DateTimeKind.Utc);
        _domainEvents.Add(new VendorPaid(Id, occurrence, fundingSource, paidByUserId, DateTime.UtcNow));
    }

    /// <summary>Undo the vendor payment for an occurrence (the ledger reversal is posted by the
    /// application layer). The funding of record is left in place as the intended default.</summary>
    public void ReverseVendorPayment(DateTime occurrenceDate)
    {
        if (GroupId is null)
            throw new InvalidOperationException("Vendor payment applies to group expenses only.");

        UpdatedAt = DateTime.UtcNow;
        var occurrence = DateTime.SpecifyKind(occurrenceDate.Date, DateTimeKind.Utc);
        _domainEvents.Add(new VendorPaymentReversed(Id, occurrence));
    }
}
