using Finance.Domain.ValueObjects;

namespace Infrastructure.Plaid.Mirrors;

// Generated by our own analysis after each sync: one suggestion per non-pending, unlinked
// transaction.
public sealed class BankSyncSuggestion
{
    public Guid Id { get; private set; }
    public FinancialConnectionId ConnectionId { get; private set; }
    public UserId UserId { get; private set; }

    public string ExternalTransactionId { get; private set; } = string.Empty;

    public string Name { get; private set; } = string.Empty;
    public string? MerchantName { get; private set; }
    public decimal Amount { get; private set; }
    public string Currency { get; private set; } = "USD";

    public RecurringFlowDirection Direction { get; private set; }

    public DateTime TransactionDate { get; private set; }
    public bool Dismissed { get; private set; }
    public bool IsLinked { get; private set; }
    public Guid? LinkedEntityId { get; private set; }
    public string? LinkedEntityType { get; private set; }
    public DateTime CreatedAt { get; private set; }

    private BankSyncSuggestion() { }

    public static BankSyncSuggestion Create(
        FinancialConnectionId connectionId,
        UserId userId,
        string externalTransactionId,
        string name,
        string? merchantName,
        decimal amount,
        string currency,
        RecurringFlowDirection direction,
        DateTime transactionDate)
    {
        return new BankSyncSuggestion
        {
            Id = Guid.NewGuid(),
            ConnectionId = connectionId,
            UserId = userId,
            ExternalTransactionId = externalTransactionId,
            Name = name ?? string.Empty,
            MerchantName = merchantName,
            Amount = amount,
            Currency = string.IsNullOrWhiteSpace(currency) ? "USD" : currency.ToUpperInvariant(),
            Direction = direction,
            TransactionDate = DateTime.SpecifyKind(transactionDate.Date, DateTimeKind.Utc),
            Dismissed = false,
            IsLinked = false,
            CreatedAt = DateTime.UtcNow,
        };
    }

    public void Dismiss() => Dismissed = true;

    public void MarkLinked(Guid entityId, string entityType)
    {
        LinkedEntityId = entityId;
        LinkedEntityType = entityType;
        IsLinked = true;
    }
}
