using Finance.Domain.ValueObjects;

namespace Finance.Application.Dtos;

/// <summary>Whose books the charge lands in. The wire's word for
/// <see cref="Finance.Domain.ValueObjects.EntityKind"/>.</summary>
public enum ChargeScope
{
    Personal,
    Group
}

// Fields specific to one scope are nullable; Scope is the discriminator.
public sealed record ChargeResponseDto(
    Guid ChargeId,
    ChargeScope Scope,
    // Whose books it lands in: a household id when Scope is Group, a person's when Personal. One
    // field, because three (userId/groupId/createdBy) said it between them and disagreed about
    // what userId meant.
    Guid OwnerId,
    // The person who wrote it down — the same person as OwnerId on a personal charge.
    Guid EnteredBy,
    string Title,
    string? Description,
    decimal Amount,
    string Currency,
    ChargeCategory Category,
    DateTime DueDate,
    bool IsActive,
    DateTime CreatedAt,
    DateTime UpdatedAt,
    bool IsPaid = false,            // Personal: paid status. Group: caller's *share* pay status (CallerIsPaid).
    DateTime? CurrentOccurrenceDate = null,
    // Set when this bill was generated by a repeating agreement. The cadence itself is NOT here —
    // it belongs to the schedule, and a copy on the bill is what let the two disagree before.
    Guid? ScheduleId = null,
    Guid? PayerUserId = null,
    FundingSource? FundingSource = null,    // set when Scope == Group; null for personal
    // Group only: has the VENDOR been paid (the bill itself), which is distinct from the caller's own
    // share (IsPaid). Derived from the ledger's Vendor Payable balance. Legacy cash-basis charges
    // never touched that account, so they read as vendor-paid.
    bool VendorPaid = false,
    // Group only: the caller's own allocation on this charge. Null when they have no allocation, and
    // on personal charges.
    decimal? CallerShare = null);

public sealed record ChargeListDto(IReadOnlyCollection<ChargeResponseDto> Items, int TotalCount);

public sealed record GroupChargeListDto(IReadOnlyCollection<ChargeResponseDto> Items, int TotalCount);

public sealed record AllocationDetailDto(
    Guid AllocationId,
    Guid UserId,
    string? DisplayName,
    string? AvatarUrl,
    string MembershipRole,
    decimal Amount,
    string Currency,
    bool IsPaid);

public sealed record GroupChargeDetailDto(
    ChargeResponseDto Charge,
    IReadOnlyCollection<AllocationDetailDto> Allocations);

public sealed record AllocationDto(
    Guid AllocationId,
    Guid ChargeId,
    Guid UserId,
    decimal Amount,
    string Currency,
    bool IsPaid,
    DateTime CreatedAt,
    DateTime UpdatedAt);

public sealed record CallerAllocationStatusDto(Guid AllocationId, bool IsPaid);
