using Finance.Domain.ValueObjects;

namespace Finance.Application.Dtos;

/// <summary>Whose books the expense lands in. The wire's word for
/// <see cref="Finance.Domain.ValueObjects.EntityKind"/>.</summary>
public enum ExpenseScope
{
    Personal,
    Group
}

// Fields specific to one scope are nullable; Scope is the discriminator.
public sealed record ExpenseResponseDto(
    Guid ExpenseId,
    ExpenseScope Scope,
    // Whose books it lands in: a household id when Scope is Group, a person's when Personal. One
    // field, because three (userId/groupId/createdBy) said it between them and disagreed about
    // what userId meant.
    Guid OwnerId,
    // The person who wrote it down — the same person as OwnerId on a personal expense.
    Guid EnteredBy,
    string Title,
    string? Description,
    decimal Amount,
    string Currency,
    ExpenseCategory Category,
    DateTime DueDate,
    bool IsActive,
    DateTime CreatedAt,
    DateTime UpdatedAt,
    bool IsPaid = false,            // Personal: paid status. Group: caller's *share* pay status (CallerIsPaid).
    DateTime? CurrentOccurrenceDate = null,
    // Set when this bill was generated by a repeating agreement. The cadence itself is NOT here —
    // it belongs to the schedule, and a copy on the bill is what let the two disagree before.
    Guid? RecurringExpenseId = null,
    Guid? PayerUserId = null,
    FundingSource? FundingSource = null,    // set when Scope == Group; null for personal
    // Group only: has the VENDOR been paid (the bill itself), which is distinct from the caller's own
    // share (IsPaid). Derived from the ledger's Vendor Payable balance. Legacy cash-basis expenses
    // never touched that account, so they read as vendor-paid.
    bool VendorPaid = false,
    // Group only: the caller's own share on this expense. Null when they have no share, and
    // on personal expenses.
    decimal? CallerShare = null);

public sealed record ExpenseListDto(IReadOnlyCollection<ExpenseResponseDto> Items, int TotalCount);

public sealed record GroupExpenseListDto(IReadOnlyCollection<ExpenseResponseDto> Items, int TotalCount);

public sealed record ShareDetailDto(
    Guid ShareId,
    Guid UserId,
    string? DisplayName,
    string? AvatarUrl,
    string MembershipRole,
    decimal Amount,
    string Currency,
    bool IsPaid);

public sealed record GroupExpenseDetailDto(
    ExpenseResponseDto Expense,
    IReadOnlyCollection<ShareDetailDto> Shares);

public sealed record ShareDto(
    Guid ShareId,
    Guid ExpenseId,
    Guid UserId,
    decimal Amount,
    string Currency,
    bool IsPaid,
    DateTime CreatedAt,
    DateTime UpdatedAt);

public sealed record CallerShareStatusDto(Guid ShareId, bool IsPaid);
